// Banco de dados dos produtos
const data = [
  {
    id: 1,
    img: "./img/jaqueta.svg",
    nameItem: "Lightweight Jacket",
    description:
      "Adicione um pouco de energia ao seu guarda-roupa de inverno com esta jaqueta vibrante...",
    value: 100,
    addCart: "Adicionar ao carrinho",
    tag: ["Camisetas"],
    keyWord: [
      "Lightweight Jacket",
      "Camisetas",
      "Camisas",
      "Jaquetas",
      "Pretos",
      "Pretas",
      "Blusas",
      "Moletom",
      "Moletons",
      "Inverno",
      100,
    ],
  },
  {
    id: 2,
    img: "./img/gorro.svg",
    nameItem: "Black Hat",
    description:
      "O gorro Next.js chegou! Esta beldade bordada tem um ajuste confortável que garante que...",
    value: 65.99,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
    keyWord: [
      "Black Hat",
      "Gorro",
      "Touca",
      "Preto",
      "Preta",
      "Inverno",
      "Acessórios",
      65.99,
    ],
  },
  {
    id: 3,
    img: "./img/mascara.svg",
    nameItem: "Mask",
    description:
      "Esta máscara facial durável é feita de duas camadas de tecido tratado e possui presilhas...",
    value: 30,
    addCart: "Adicionar ao carrinho",
    tag: ["Acessórios"],
    keyWord: [
      "Mask",
      "Mascara",
      "Máscara",
      "Preto",
      "Preta",
      "Casual",
      "Acessórios",
      30,
    ],
  },
  {
    id: 4,
    img: "./img/camiseta_preta.svg",
    nameItem: "T-Shirt Preta",
    description:
      "Esta t-shirt é imprescindível no seu guarda-roupa, combinando o caimento intemporal de...",
    value: 70,
    addCart: "Adicionar ao carrinho",
    tag: ["Camisetas"],
    keyWord: [
      "T-Shirt Preta",
      "Camisas",
      "Preto",
      "Preta",
      "Casual",
      "Camisetas",
      70,
    ],
  },
  {
    id: 5,
    img: "./img/tenis-puma.png",
    nameItem: "Puma Ignite",
    description:
      "Ideal para o dia-a-dia, o tênis Puma ignite fornece a você o conforto necessário para...",
    value: 150,
    addCart: "Adicionar ao carrinho",
    tag: ["Calçados"],
    keyWord: [
      "Puma Ignite",
      "Sapatos",
      "Preto",
      "Preta",
      "Fit",
      "Corrida",
      "Calçados",
      "Calcados",
      "Tênis",
      "Tenis",
      150,
    ],
  },
  {
    id: 6,
    img: "./img/camiseta_branca.svg",
    nameItem: "Short-Sleeve T-Shirt",
    description:
      "Agora você encontrou a camiseta básica do seu guarda-roupa. É feito de um mais grosso...",
    value: 50,
    addCart: "Adicionar ao carrinho",
    tag: ["Camisetas"],
    keyWord: [
      "Short-Sleeve T-Shirt",
      "Camisas",
      "Branco",
      "Branca",
      "Casual",
      "Camisetas",
      50,
    ],
  },
  {
    id: 7,
    img: "./img/moletom.svg",
    nameItem: "Champion Packable Jacket",
    description:
      "Proteja-se dos elementos com esta jaqueta embalável Champion. Esta jaqueta de poliést...",
    value: 200,
    addCart: "Adicionar ao carrinho",
    tag: ["Camisetas"],
    keyWord: [
      "Champion Packable Jacket",
      "Camiseta",
      "Camisa",
      "Jaqueta",
      "Preto",
      "Preta",
      "Blusa",
      "Moletom",
      "Moletons",
      "Inverno",
      "Gorro",
      "Campeão",
      200,
    ],
  },
  {
    id: 8,
    img: "./img/Air-Jordan-PNG-File.png",
    nameItem: "Nike Air Jordan",
    description:
      "Talvez o tênis mais emblemático de todos os tempos, esta coloração original 'Chicago' é...",
    value: 175.5,
    addCart: "Adicionar ao carrinho",
    tag: ["Calçados"],
    keyWord: [
      "Nike Air Jordan",
      "Tênis",
      "Tenis",
      "Calçados",
      "Calcados",
      "Vermelho",
      "Preto",
      "Branco",
      "Casual",
      "Sapatos",
      100,
    ],
  },
  {
    id: 9,
    img: "./img/adidas-runfalcon.png",
    nameItem: "Adidas Runfalcon",
    description:
      "A escolha para seu momento fit. O tênis Adidas Runfalcon foi desenvolvido com a tecnologia...",
    value: 250,
    addCart: "Adicionar ao carrinho",
    tag: ["Calçados"],
    keyWord: [
      "Adidas Runfalcon",
      "Tênis",
      "Tenis",
      "Calçados",
      "Calcados",
      "Azul",
      "Branco",
      "Fit",
      "Corrida",
      "Sapatos",
      100,
    ],
  },
];
